### ISSUE TITLE
Vendor endpoint is not ready for provider calls when resuming from pod crash

### ISSUE THREAD

**Issue by RemindD** [eclipse-symphony/symphony#580]
Scenario:
1. An activation activates a campaign and pod crashes when one of the stages is running
2. pod resumes
3. pubsub state provider is resumed first, starting to retrieve pending messages from redis server. 
4. One of the stages resumes from the trigger events and execute the provider. The provider may send requests for symphony objects CRUD operation to vendor endpoints. However, the vendor may be not ready at this point so the provider fails.
5. the trigger events save "Failed" result in the activation and completed successfully.

Result: All the stages which failed to call vendor endpoints will end with Failed result and stops activation execution.

**Comment by msftcoderdjw** [comment]
We will consider to add retry in apiclient to keep retrying in retriable error.

**Comment by linyguo** [comment]
When pod restart, processMessage should wait for evaluation initialization complete.

Callstack:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x21cd33b]

goroutine 55 [running]:
github.com/eclipse-symphony/symphony/api/pkg/apis/v1alpha1/managers/stage.(*StageManager).traceValue(0xc000119d40, {0x2d1f888, 0xc000020ed0}, {0x23b2a20?, 0xc000820a90?}, {0xc0003aab50, 0xa}, 0xc00081ed80, 0xc0001c0db0, 0x0)
	/workspace/api/pkg/apis/v1alpha1/managers/stage/stage-manager.go:805 +0x13b
github.com/eclipse-symphony/symphony/api/pkg/apis/v1alpha1/managers/stage.(*StageManager).traceValue(0xc000119d40, {0x2d1f888, 0xc000020ed0}, {0x2376e80?, 0xc0000d2d80?}, {0xc0003aab50, 0xa}, 0xc00081ed80, 0xc0001c0db0, 0x0)
	/workspace/api/pkg/apis/v1alpha1/managers/stage/stage-manager.go:831 +0x759
github.com/eclipse-symphony/symphony/api/pkg/apis/v1alpha1/managers/stage.(*StageManager).HandleTriggerEvent(_, {_, _}, {{0xc00082431c, 0x4}, 0xc00081eab0, 0x1, {0x0, 0x0}, {0xc000824330, ...}}, ...)
	/workspace/api/pkg/apis/v1alpha1/managers/stage/stage-manager.go:512 +0x158b
github.com/eclipse-symphony/symphony/api/pkg/apis/v1alpha1/vendors.(*StageVendor).Init.func2({0xc000100008?, 0xc000507d80?}, {0xc0001c0a50, {0x24e7c60, 0xc0001c0a80}, {0x2d1f888, 0xc0001c0b70}})
	/workspace/api/pkg/apis/v1alpha1/vendors/stage-vendor.go:191 +0xb38
github.com/eclipse-symphony/symphony/coa/pkg/apis/v1alpha2.EventShouldRetryWrapper({0xc0004e5c20?, {0x0?, 0x3?}}, {0x28edadf?, 0x0?}, {0xc0001c0a50, {0x24e7c60, 0xc0001c0a80}, {0x2d1f888, 0xc0001c0b70}})
	/workspace/coa/pkg/apis/v1alpha2/events.go:197 +0x6f
github.com/eclipse-symphony/symphony/coa/pkg/apis/v1alpha2/providers/pubsub/redis.(*RedisPubSubProvider).processMessage(0xc0000ccc60, {0x28edadf, 0x7}, {0xc0004e5c20?, {0x0?, 0x603bc4?}}, 0xc000010510)
	/workspace/coa/pkg/apis/v1alpha2/providers/pubsub/redis/redis.go:330 +0x647
created by github.com/eclipse-symphony/symphony/coa/pkg/apis/v1alpha2/providers/pubsub/redis.(*RedisPubSubProvider).reclaimPendingMessages in goroutine 30
	/workspace/coa/pkg/apis/v1alpha2/providers/pubsub/redis/redis.go:306 +0x36f
